export const FETCH_SMILEYS = {
  value: 'FETCH_SMILEYS',
  SUCCESS: 'FETCH_SMILEYS_SUCCESS',
  ERROR: 'FETCH_SMILEYS_ERROR',
  LOADING: 'FETCH_SMILEYS_LOADING',
};

export const MARK_SMILEYS_VISIBLE = 'MARK_SMILEYS_VISIBLE';

export const RESET_SMILEYS = 'RESET_SMILEYS';

export const COMPLETE_SMILEY_STORE = 'COMPLETE_SMILEY_STORE';
